---

- name: Drop all current rules
  sudo: yes
  command: iptables -F

- name: Allow request from different ports
  sudo: yes
  command: iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport {{item}} -j ACCEPT
  with_items:
   - 22     # ssh
   - 80     # http
   - 443    # https
   - 3306   # mysql
   - 8088   # epagesj
   - 8983   # solr
   - 8985   # solr
   - 27017  # mongodb
   - 28017  # mongodb diagnostics

- name: Save iptables rules
  sudo: yes
  command: service iptables save
